apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-vol6
  labels:
    path: nfsshare6
    type: redis-nfs
    app: redis
    podindex: "5"
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.1.1
    path: "/data/store/share/n6"