apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-vol1
  labels:
    path: nfsshare1
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.1.1
    path: "/home/nfs/nfsshare1"