apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-vol5
  labels:
    path: nfsshare5
    type: redis-nfs
    app: redis
    podindex: "4"
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.1.1
    path: "/data/store/share/n5"